### ISSUE TITLE
Code created for Sample Data

### ISSUE THREAD

**Issue by Shirlett** [amjoo/LIBR554_DBD#1]
See the file

**Comment by Shirlett** [comment]
Using the full code. The database is created with no errors and the sample data is loaded with no errors. 
Need to look at the dependency diagram to see whether all the connections work as intended.
I also made minor edits to the ERD for Purchase_order and made changes to the Visio diagram. I just sent you the updated Word Document.

**Comment by amjoo** [comment]
Did you update the master git with the working code? I'm still seeing code referring to ORDER instead of PURCHASE_ORDER. 

Awesome! Will add that to the document tomorrow.

**Comment by Shirlett** [comment]
Yes I updated the master code. I left order_item as is though.

**Comment by amjoo** [comment]
It works!! Seems like my updates are delayed on Git. :/

**Comment by Shirlett** [comment]
Maybe I just had not committed yet so you could not see the change. I just made another update for the self-referencing table PRODUCT. I ran the script and casually looked at the dependency diagram created by SQL and it looks ok right now but I need to compare our ERD with it. Can you also take a look, so we don't miss anything?

**Comment by amjoo** [comment]
Ah!! Okay makes sense! I uploaded onto my end and it works now! I just woke up a little while ago and will review the dependency diagram with the current ERD. : )
