### ISSUE TITLE
Syntax for Auto_Increment in SQL Server 

### ISSUE THREAD

**Issue by amjoo** [amjoo/LIBR554_DBD#2]
`CREATE TABLE Persons (
    ID int IDENTITY(1,1) PRIMARY KEY,
    LastName varchar(255) NOT NULL,
    FirstName varchar(255),
    Age int
);`
[https://www.w3schools.com/sql/sql_autoincrement.asp](url)

**Comment by Shirlett** [comment]
Cool, I was just checking why this was not working when you sent this email :D
I just did a test creation of all the tables, and they went in. I had to change ORDER to PURCHASE_ORDER because 'order' is a keyword/reserved word in sql.

**Comment by amjoo** [comment]
HAHA I was just about to comment about that ORDER problem. Thanks for getting that!
